//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace controle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_COMMANDE
    {
        public int IDCommande { get; set; }
        public int IDProduit { get; set; }
        public Nullable<int> Qte { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
